version: 2
updates:
  - package-ecosystem: cargo
    directory: "/clorinde"
    schedule:
      interval: daily
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
