name: 🐞 Bug Report
description: Report a bug
type: Bug

body:
  - type: markdown
    attributes:
      value: |
        ## First of all
        1. Please search for [existing issues](https://github.com/halcyonnouveau/clorinde/issues?q=is%3Aissue) about this problem first.
        2. Make sure `rustc` and `clorinde` is up to date.
        3. Make sure it's an issue with Clorinde and not something else you are using.
        4. Remember to follow our community guidelines and be friendly.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A link to a reproduction repo or steps to reproduce the behaviour.
      placeholder: |
        Please provide a minimal reproduction or steps to reproduce, see this guide https://stackoverflow.com/help/minimal-reproducible-example
        Why reproduction is required? see this article https://antfu.me/posts/why-reproductions-are-required
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please include and logs/stack traces the time this bug occurred. Optional if provided reproduction. Please try not to insert an image but copy paste the log text.
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity of this issue
      options:
        - Annoyance
        - Blocking an upgrade
        - Blocking all usage of Clorinde
    validations:
      required: true
