// Re-export all types generated by clorinde
include!(concat!(env!("OUT_DIR"), "/lib.rs"));

// Re-export postgres-types and other essential dependencies
pub use deadpool_postgres;
pub use postgres_types;
pub use tokio_postgres;
